routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();


Route::group(['middleware' => ['auth']], function () {
	
	Route::get('/', 'HomeController@index')->name('dashboard.index');
	Route::resource('/rencana-kegiatan', 'RencanaController');
	Route::get('/realisasi-kegiatan/{id_timesheet}/create', 'RealisasiController@create');
	Route::resource('/realisasi-kegiatan', 'RealisasiController')->except('create');
    Route::post('job-order/nilai', 'JobOrderController@addNilai')->name('job-order.add-nilai');
	Route::get('/job-order/{timesheet_id}/comment', 'JobOrderController@comment')->name('job-order.comment');
	Route::post('/job-order/{timesheet_id}/comment', 'JobOrderController@storeComment')->name('job-order.store-comment');
    Route::post('/job-order/{employee_id}', 'JobOrderController@store')->name('job-order.store');
	Route::resource('/job-order', 'JobOrderController')->except('store');
	Route::get('/report', 'ReportController@index')->name('report.index');
	Route::post('/report', 'ReportController@show')->name('report.show');
	Route::get('/chart', 'ChartController@index')->name('chart.index');
	Route::post('/chart', 'ChartController@show')->name('chart.show');

	Route::group(['middleware' => ['role:Admin']], function () {
        Route::resource('/users', 'UserController');
        Route::resource('/tanggal-libur', 'TanggalLiburController');

	});

});

Route::get('/asd', 'ChartController@asd');

Route::get('/home', function(){
    return redirect('/');
});

resources/views/realisasi-kegiatan/_form.blade.php
<br>
@csrf
<input type="hidden" name="idTimeSheet" value="{{ $timesheet->idTimeSheet }}">

<div class="form-group row">
  <label for="time_from" class="col-md-2 col-form-label text-md-right">Jam Mulai</label>
  <div class="col-md-6">
    <div class="input-group date timepicker" id="time_from" data-target-input="nearest">
      
      <input type="text" name="time_from_act" class="form-control datetimepicker-input" data-target="#time_from" placeholder="hh:mm" value="{{ old('time_from_act', 
      isset($activity) ? $activity->time_from_act->format('H:i') : ($timesheet->time_from->format('H:i') ?? '')) }}" />
      
      <div class="input-group-append" data-target="#time_from" data-toggle="datetimepicker">
          <div class="input-group-text"><i class="far fa-clock"></i></div>
      </div>
    </div>
  </div>
</div>

<div class="form-group row">
  <label for="time_to" class="col-md-2 col-form-label text-md-right">Jam Selesai</label>
  <div class="col-md-6">
    <div class="input-group date timepicker" id="time_to" data-target-input="nearest">
      
      <input type="text" name="time_to_act" class="form-control datetimepicker-input" data-target="#time_to" placeholder="hh:mm" value="{{ 
      old('time_to_act', 
      isset($activity) ? $activity->time_to_act->format('H:i') : ($timesheet->time_to->format('H:i') ?? '')) }}"/>

      <div class="input-group-append" data-target="#time_to" data-toggle="datetimepicker">
          <div class="input-group-text"><i class="far fa-clock"></i></div>
      </div>
    </div>
  </div>
</div>

<div class="form-group row">
  <label for="realisasiEmployee" class="col-md-2 col-form-label text-md-right">Rencana / Kegiatan</label>
  <div class="col-md-6">
    
    <textarea class="textarea form-control" rows="5" name="realisasiEmployee" id="realisasiEmployee" placeholder="Apa yang akan Anda lakukan ?">{{ old('realisasiEmployee', $activity->realisasiEmployee ?? '') }}</textarea>
  
  </div>
</div>

<div class="form-group row">
  <label class="col-md-2"></label>
  <div class="col-md-6">
    <button type="submit" class="btn btn-primary">Submit</button>
    <button type="reset" class="btn btn-danger">Reset</button>
  </div>
</div>

resources/views/realisasi-kegiatan/create.blade.php
@extends('layouts.main')

@section('title', 'Realisasi Kegiatan')

@section('content')
    <div class="row">
      <div class="col-lg-12">

        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Rencana Kegiatan</h3>
            </div>
            <!-- /.card-header -->
            
            <div class="card-body">
                <div class="form-group row">
                  <label class="col-md-2 col-form-label text-md-right">Rencana</label>
                  <div class="col-md-6">
                    <div class="input-group date timepicker" id="time_from" data-target-input="nearest">                      
                      <div class="form-control" readonly="readonly">
                        {{ $timesheet->rencanaEmployee }}
                      </div>                      
                    </div>
                  </div>
                </div>

                <div class="form-group row">
                  <label class="col-md-2 col-form-label text-md-right">Tanggal</label>
                  <div class="col-md-6">
                    <div class="input-group date timepicker" id="time_from" data-target-input="nearest">                      
                      <div class="form-control" readonly="readonly">
                        {{ $timesheet->date->format('d-m-Y') }}
                      </div>                      
                    </div>
                  </div>
                </div>

                <div class="form-group row">
                  <label class="col-md-2 col-form-label text-md-right">Dari</label>
                  <div class="col-md-6">
                    <div class="input-group date timepicker" id="time_from" data-target-input="nearest">                      
                      <div class="form-control" readonly="readonly">
                        {{ $timesheet->time_from->format('H:i') }}</p>
                      </div>                      
                    </div>
                  </div>
                </div>

                <div class="form-group row">
                  <label class="col-md-2 col-form-label text-md-right">Sampai</label>
                  <div class="col-md-6">
                    <div class="input-group date timepicker" id="time_from" data-target-input="nearest">                      
                      <div class="form-control" readonly="readonly">
                        {{ $timesheet->time_to->format('H:i') }}
                      </div>                      
                    </div>
                  </div>
                </div>
              </div>
            </div>


        <div class="card card-success">
            <div class="card-header">
                <h3 class="card-title">Input Realisasi Kegiatan</h3>
            </div>
            <br>
                <form action="{{ route('realisasi-kegiatan.store') }}" method="POST">
                    @include('realisasi-kegiatan._form')
                </form>
            </div>
        </div>
          
      </div>
    </div>
    <!-- /.row -->
@endsection

resources/views/realisasi-kegiatan/edit.blade.php
@extends('layouts.main')

@section('title', 'Edit Realisasi Kegiatan')

@section('content')
    <div class="row">
      <div class="col-lg-12">

        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title"> Realisasi Kegiatan</h3>
            </div>
            <!-- /.card-header -->
            
            <div class="card-body">
                <div class="form-group row">
                  <label class="col-md-2 col-form-label text-md-right">Rencana</label>
                  <div class="col-md-6">
                    <div class="input-group date timepicker" id="time_from" data-target-input="nearest">                      
                      <div class="form-control" readonly="readonly">
                       {{ $timesheet->rencanaEmployee }}
                      </div>                      
                    </div>
                  </div>
                </div>

                <div class="form-group row">
                  <label class="col-md-2 col-form-label text-md-right">Tanggal</label>
                  <div class="col-md-6">
                    <div class="input-group date timepicker" id="time_from" data-target-input="nearest">                      
                      <div class="form-control" readonly="readonly">
                       {{ $timesheet->date->format('d-m-Y') }}
                      </div>                      
                    </div>
                  </div>
                </div>

                <div class="form-group row">
                  <label class="col-md-2 col-form-label text-md-right">Dari</label>
                  <div class="col-md-6">
                    <div class="input-group date timepicker" id="time_from" data-target-input="nearest">                      
                      <div class="form-control" readonly="readonly">
                      {{ $timesheet->time_from->format('H:i') }}
                      </div>                      
                    </div>
                  </div>
                </div>

                <div class="form-group row">
                  <label class="col-md-2 col-form-label text-md-right">Sampai</label>
                  <div class="col-md-6">
                    <div class="input-group date timepicker" id="time_from" data-target-input="nearest">                      
                      <div class="form-control" readonly="readonly">
                     {{ $timesheet->time_to->format('H:i') }}
                      </div>                      
                    </div>
                  </div>
                </div>
              </div>
            </div>
                

        <div class="card card-success">
            <div class="card-header">
                <h3 class="card-title">Edit Realisasi Kegiatan</h3>
            </div>
            <br>
                <form action="{{ route('realisasi-kegiatan.update', $activity) }}" method="POST">
                    @method('PUT')
                    @include('realisasi-kegiatan._form')
                </form>
            </div>
        </div>
          
      </div>
    </div>
    <!-- /.row -->
@endsection

resources/views/realisasi-kegiatan/index.blade.php
@extends('layouts.main')

@section('title', 'Realisasi Kegiatan')

@section('content')
<div class="row">
    <div class="col-lg-12">

        <div class="card card-success">
            <div class="card-header">
                <h3 class="card-title">Agenda Kegiatan Minggu ini</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body p-0">
                <table class="table table-bordered table-hover table-responsive">
                    <thead>
                        <tr class="text-center">
                            <th class="align-middle" rowspan="2">No.</th>
                            <th class="align-middle" rowspan="2">Tanggal</th>
                            <th class="align-middle" colspan="2">Waktu Rencana</th>
                            <th class="align-middle" rowspan="2">Rencana Kegiatan</th>
                            <th class="align-middle" colspan="2">Waktu Realisasi</th>
                            <th class="align-middle" rowspan="2">Realisasi Kegiatan</th>
                            <th class="align-middle" colspan="2">Komentar</th>
                            <th class="align-middle" rowspan="2">Action</th>
                            <th class="align-middle" rowspan="2">Keterangan</th>
                        </tr>
                        <tr class="text-center">
                            <th>Jam Mulai</th>
                            <th>Jam Selesai</th>
                            <th>Jam Mulai</th>
                            <th>Jam Selesai</th>
                            <th>Ka. Biro / Manajer</th>
                            <th>Direksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($timesheets as $timesheet)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $timesheet->date->format('d-m-Y')}}</td>
                            <td>{{ $timesheet->time_from->format('H:i')}}</td>
                            <td>{{ $timesheet->time_to->format('H:i')}}</td>
                            <td>{{ $timesheet->rencanaEmployee }}</td>
                            <td>{{ isset($timesheet->activity) ? $timesheet->activity->time_from_act->format('H:i') : ''}}</td>
                            <td>{{ isset($timesheet->activity) ? $timesheet->activity->time_to_act->format('H:i') : '' }}</td>
                            <td>{{ $timesheet->activity->realisasiEmployee ?? '' }}</td>
                            @if($timesheet->kabid_comments > 0)
                            <td><a href="{{ route('job-order.comment', $timesheet->idTimeSheet) }}" class="btn btn-sm btn-danger">{{ $timesheet->kabid_comments }} Komentar</a></td>
                            @else
                            <td></td>
                            @endif
                            @if($timesheet->direksi_comments > 0)
                            <td><a href="{{ route('job-order.comment', $timesheet->idTimeSheet) }}" class="btn btn-sm btn-danger">{{ $timesheet->direksi_comments }} Komentar</a></td>
                            @else
                            <td></td>
                            @endif
                            <td>
                        
                                @if($timesheet->date->startOfDay() == now()->startOfDay())               

                                @if(!isset($timesheet->activity))
                               
                                <a class="btn btn-sm btn-primary" href="{{ 'realisasi-kegiatan/'.$timesheet->idTimeSheet.'/create' }}">Input</a>
                                @endif

                                @isset($timesheet->activity)
                                <a class="btn btn-sm btn-warning" href="{{ route('realisasi-kegiatan.edit', $timesheet->activity->idActivity) }}">Edit</a>
                                @endisset
                         
                                @endif
                            
                            </td>
                            <td></td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <div class="card-footer">
                {{ $timesheets->links() }}
            </div>
        </div>

    </div>
</div>
<!-- /.row -->
@endsection