routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();


Route::group(['middleware' => ['auth']], function () {
	
	Route::get('/', 'HomeController@index')->name('dashboard.index');
	Route::resource('/rencana-kegiatan', 'RencanaController');
	Route::get('/realisasi-kegiatan/{id_timesheet}/create', 'RealisasiController@create');
	Route::resource('/realisasi-kegiatan', 'RealisasiController')->except('create');
    Route::post('job-order/nilai', 'JobOrderController@addNilai')->name('job-order.add-nilai');
	Route::get('/job-order/{timesheet_id}/comment', 'JobOrderController@comment')->name('job-order.comment');
	Route::post('/job-order/{timesheet_id}/comment', 'JobOrderController@storeComment')->name('job-order.store-comment');
    Route::post('/job-order/{employee_id}', 'JobOrderController@store')->name('job-order.store');
	Route::resource('/job-order', 'JobOrderController')->except('store');
	Route::get('/report', 'ReportController@index')->name('report.index');
	Route::post('/report', 'ReportController@show')->name('report.show');
	Route::get('/chart', 'ChartController@index')->name('chart.index');
	Route::post('/chart', 'ChartController@show')->name('chart.show');

	Route::group(['middleware' => ['role:Admin']], function () {
        Route::resource('/users', 'UserController');
        Route::resource('/tanggal-libur', 'TanggalLiburController');

	});

});

Route::get('/asd', 'ChartController@asd');

Route::get('/home', function(){
    return redirect('/');
});

resources/views/layouts/parts/menu.blade.php
<!-- Sidebar Menu -->
<nav class="mt-2">
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
         with font-awesome or any other icon font library -->
        {{--
    <!--
    <li class="nav-item has-treeview menu-open">
      <a href="#" class="nav-link active">
        <i class="nav-icon fas fa-tachometer-alt"></i>
        <p>
          Starter Pages
          <i class="right fas fa-angle-left"></i>
        </p>
      </a>
      <ul class="nav nav-treeview">
        <li class="nav-item">
          <a href="#" class="nav-link active">
            <i class="far fa-circle nav-icon"></i>
            <p>Active Page</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="far fa-circle nav-icon"></i>
            <p>Inactive Page</p>
          </a>
        </li>
      </ul>
    </li>
    <li class="nav-item">
      <a href="#" class="nav-link">
        <i class="nav-icon fas fa-th"></i>
        <p>
          Simple Link
          <span class="right badge badge-danger">New</span>
        </p>
      </a>
    </li>
    -->
    --}}
        <li class="nav-item">
            <a href="{{ route('dashboard.index') }}" class="nav-link {{ (request()->is('/')) ? 'active' : '' }}">
                <i class="nav-icon fas fa-th"></i>
                <p>Dashboard</p>
            </a>
        </li>
        @hasanyrole('KaBiro|GM|Manager|Staff')       
        <li class="nav-item">
            <a href="{{ route('rencana-kegiatan.index') }}" class="nav-link {{ (request()->is('rencana-kegiatan*')) ? 'active' : '' }}">
                <i class="nav-icon fas fa-calendar-plus"></i>
                <p>Rencana Kegiatan</p>
            </a>
        </li>
        @endhasanyrole
        @hasanyrole('KaBiro|GM|Manager|Staff') 
        <li class="nav-item">
            <a href="{{ route('realisasi-kegiatan.index') }}" class="nav-link {{ (request()->is('realisasi-kegiatan*')) ? 'active' : '' }}">
                <i class="nav-icon fas fa-calendar-check"></i>
                <p>Realisasi Kegiatan</p>
            </a>
        </li>
        @endhasanyrole
        @hasanyrole('KaBiro|Direksi|GM|Manager|Admin')
        <li class="nav-item">
            <a href="{{ route('job-order.index') }}" class="nav-link {{ (request()->is('job-order*')) ? 'active' : '' }}">
                <i class="nav-icon fas fa-exclamation"></i>
                <p>Job Order Kegiatan Staff</p>
            </a>
        </li>
        @endhasanyrole
        @hasanyrole('KaBiro|Direksi|GM|Manager|Admin')       
        <li class="nav-item">
            <a href="{{ route('report.index') }}" class="nav-link {{ (request()->is('report*')) ? 'active' : '' }}">
                <i class="nav-icon fas fa-clipboard"></i>
                <p>Report each division</p>
            </a>
        </li>
        @endhasanyrole
        @hasanyrole('KaBiro|Direksi|GM|Manager|Admin')     
        <li class="nav-item">
            <a href="{{ route('chart.index') }}" class="nav-link {{ (request()->is('chart*')) ? 'active' : '' }}">
                <i class="nav-icon fas fa-chart-bar"></i>
                <p>Chart isian Daily Activity</p>
            </a>
        </li>
        @endhasanyrole
        @hasanyrole('Staff|Admin|Manager|KaBiro')      
        <li class="nav-item">
            <a href="{{ route('realisasi-kegiatan.index') }}" class="nav-link {{ (request()->is('realisasi-kegiatan*')) ? 'active' : '' }}">
                <i class="nav-icon fas fa-history"></i>
                <p>Agenda Kegiatan</p>
            </a>
        </li>
        @endhasanyrole
        @hasanyrole('Admin')      
        <li class="nav-item">
            <a href="{{ route('users.index') }}" class="nav-link {{ (request()->is('users*')) ? 'active' : '' }}">
                <i class="nav-icon fas fa-users"></i>
                <p>Users</p>
            </a>
        </li>
        @endhasanyrole
        @hasanyrole('Admin')      
        <li class="nav-item">
            <a href="{{ route('tanggal-libur.index') }}" class="nav-link {{ (request()->is('tanggal-libur*')) ? 'active' : '' }}">
                <i class="nav-icon fas fa-calendar"></i>
                <p>Input tanggal libur</p>
            </a>
        </li>
        @endhasanyrole
    </ul>
</nav>
<!-- /.sidebar-menu -->

resources/views/layouts/parts/notification.blade.php
<!-- Notifications Dropdown Menu -->
<!-- HIDEO
<li class="nav-item dropdown">
    <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="far fa-bell"></i>
        <span class="badge badge-warning navbar-badge">15</span>
    </a>

    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <span class="dropdown-header">4 Notifications</span>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
        </a>
<!--
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
        </a>
-->
<!--
        <div class="dropdown-divider"></div>
        <a href="realisasi-kegiatan" class="dropdown-item dropdown-footer">See All Notifications</a>
    </div>
    
</li>
-->

resources/views/layouts/parts/options.blade.php
<!-- Notifications Dropdown Menu -->
<li class="nav-item dropdown">
  <a class="nav-link" data-toggle="dropdown" href="#">
    <i class="fas fa-cog"></i>
  </a>
  
<div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
  <span class="dropdown-header">{{ optional(auth()->user())->name }}</span>
  <div class="dropdown-divider"></div>
  <a href="#" class="dropdown-item" onclick="event.preventDefault();
               document.getElementById('logout-form').submit();">
    <i class="fas fa-sign-out-alt mr-2 text-danger"></i> Logout
  </a>
  <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
      @csrf
  </form>
    <!--
  <div class="dropdown-divider"></div>
  <!-- <div class="dropdown-divider"></div>
  <a href="#" class="dropdown-item">
    <i class="fas fa-users mr-2"></i> 8 friend requests
    <span class="float-right text-muted text-sm">12 hours</span>
  </a>
  <div class="dropdown-divider"></div>
  <a href="#" class="dropdown-item">
    <i class="fas fa-file mr-2"></i> 3 new reports
    <span class="float-right text-muted text-sm">2 days</span>
  </a> 
  <a href="#" class="dropdown-item dropdown-footer"></a>
    --->
</div>
</li>