routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();


Route::group(['middleware' => ['auth']], function () {
	
	Route::get('/', 'HomeController@index')->name('dashboard.index');
	Route::resource('/rencana-kegiatan', 'RencanaController');
	Route::get('/realisasi-kegiatan/{id_timesheet}/create', 'RealisasiController@create');
	Route::resource('/realisasi-kegiatan', 'RealisasiController')->except('create');
    Route::post('job-order/nilai', 'JobOrderController@addNilai')->name('job-order.add-nilai');
	Route::get('/job-order/{timesheet_id}/comment', 'JobOrderController@comment')->name('job-order.comment');
	Route::post('/job-order/{timesheet_id}/comment', 'JobOrderController@storeComment')->name('job-order.store-comment');
    Route::post('/job-order/{employee_id}', 'JobOrderController@store')->name('job-order.store');
	Route::resource('/job-order', 'JobOrderController')->except('store');
	Route::get('/report', 'ReportController@index')->name('report.index');
	Route::post('/report', 'ReportController@show')->name('report.show');
	Route::get('/chart', 'ChartController@index')->name('chart.index');
	Route::post('/chart', 'ChartController@show')->name('chart.show');

	Route::group(['middleware' => ['role:Admin']], function () {
        Route::resource('/users', 'UserController');
        Route::resource('/tanggal-libur', 'TanggalLiburController');

	});

});

Route::get('/asd', 'ChartController@asd');

Route::get('/home', function(){
    return redirect('/');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id','name', 'nickname', 'username', 'email', 'password', 'unit_kerja_id', 'divisi_id', 'active'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function timesheets()
    {
        return $this->hasMany(Timesheet::class, 'idEmployee', 'id');
    }

    public function divisi()
    {
        return $this->hasOne(Divisi::class, 'idDivisi', 'divisi_id');
    }
    public function unitKerja()
    {
        return $this->hasOne(UnitKerja::class, 'idUnitKerja', 'unit_kerja_id');
    }

    public function scopeHasDivisi($query, $divisi_id)
    {
        return $query->where('divisi_id', $divisi_id);
    }

    public function scopeHasUnitKerja($query, $unit_kerja_id)
    {
        return $query->where('unit_kerja_id', $unit_kerja_id);
    }

    public function scopeActive($query)
    {
        return $query->where('active', 1);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Spatie\Permission\Models\Role;
use App\Models\Divisi;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $users = User::with(['divisi', 'unitKerja']);
        
        if ($request->has('search')) {
            $users->where('name', 'like', '%'.$request->search.'%');
            $users->orWhere('nickname', 'like', '%'.$request->search.'%');
            $users->orWhere('username', 'like', '%'.$request->search.'%');
        }
        $users = $users->paginate(10);

        return view('user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $divisis = Divisi::with('unit_kerjas')->get();
        
        $roles = Role::get();

        return view('user.create', compact('divisis', 'roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'username' => 'required|unique:users',
            'email' => 'required|email|unique:users',
            'password' => 'required',
            'role' => 'required',
        ]);

        $user = new User();
        $data = $request->all();
        $data['password'] = Hash::make($data['password']);
        $user = $user->create($data);

        if ($user) {
            $user->assignRole($request->role);
            return redirect(route('users.index'));
        } else {
            return redirect()->back()->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return redirect(route('users.edit', $user));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $divisis = Divisi::with('unit_kerjas')->get();
        
        $roles = Role::get();

        return view('user.edit', compact('user', 'divisis', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $request->validate([
            'username' => 'required|unique:users,username,'.$user->id,
            'email' => 'required|email|unique:users,email,'.$user->id,
            // 'password' => 'required',
            'role' => 'required',
        ]);

        $data = $request->all();
        //Hash / Delete Data Password Agar tidak kereset
        if ($data['password'] != '') {
            $data['password'] = Hash::make($data['password']);
        } else {
            unset($data['password']);
        }
        
        $user->syncRoles($data['role']);

        $user->update($data);

        if ($user) {
            return redirect(route('users.index'));
        } else {
            return redirect()->back()->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();

        return redirect()->back();
    }
}

resources/views/user/_form.blade.php
<br>
@csrf

<div class="form-group row">
  <label for="name" class="col-md-2 col-form-label text-md-right">Nama</label>
  <div class="col-md-6">
    
    <input type="text" class="form-control" rows="5" name="name" id="name" placeholder="Nama Lengkap" value="{{ old('name', $user->name ?? '') }}">
  
  </div>
</div>

<div class="form-group row">
  <label for="nickname" class="col-md-2 col-form-label text-md-right">Nickname</label>
  <div class="col-md-6">
    
    <input type="text" class="form-control" rows="5" name="nickname" id="nickname" placeholder="XXX" value="{{ old('nickname', $user->nickname ?? '') }}">
  
  </div>
</div>

<div class="form-group row">
  <label for="username" class="col-md-2 col-form-label text-md-right">Username</label>
  <div class="col-md-6">
    
    <input type="text" class="form-control" rows="5" name="username" id="username" placeholder="Digunakan Untuk Login" value="{{ old('username', $user->username ?? '') }}">
  
  </div>
</div>

<div class="form-group row">
  <label for="email" class="col-md-2 col-form-label text-md-right">Email</label>
  <div class="col-md-6">
    
    <input type="email" class="form-control" rows="5" name="email" id="email" placeholder="your@email.com" value="{{ old('email', $user->email ?? '') }}">
  
  </div>
</div>

<div class="form-group row">
  <label for="password" class="col-md-2 col-form-label text-md-right">Password</label>
  <div class="col-md-6">
    
    <input type="password" class="form-control" rows="5" name="password" id="password" placeholder="{{ isset($user) ? 'Biarkan Kosong Untuk Tidak Ganti Password' : 'Password'}}" value="{{ old('password') }}">
  
  </div>
</div>

<div class="form-group row">
  <label for="role" class="col-md-2 col-form-label text-md-right">Role</label>
  <div class="col-md-6">
    <select name="role" id="role" class="form-control">
      @foreach($roles as $role)
        <option value="{{ $role->name }}" {{ $role->name == old('role', isset($user) && count($user->roles) ? $user->roles->first()->name : 'Staff') ? 'selected' : '' }}>{{ $role->name }}</option>
      @endforeach
    </select>
  </div>
</div>

<div class="form-group row">
  <label for="divisi_id" class="col-md-2 col-form-label text-md-right">Divisi</label>
  <div class="col-md-6">
    <select name="divisi_id" id="divisi_id" class="form-control">
      @if(count($divisis) > 1)
        <option value="">Pilih Divisi</option>
      @endif
      @foreach($divisis as $divisi)
        <option value="{{ $divisi->idDivisi }}" {{ $divisi->idDivisi == old('divisi_id', $user->divisi_id ?? '') ? 'selected' : '' }}>{{ $divisi->txtDivisi }}</option>
      @endforeach
    </select>
  </div>
</div>

<!-- SELECT UNIT -->
<div class="form-group row">
  <label for="date" class="col-md-2 col-form-label text-md-right">Unit Kerja</label>
  <div class="col-md-6">
    <select name="unit_kerja_id" id="unit_kerja_id" class="form-control" data-selected="{{old('unit_kerja_id', $user->unit_kerja_id ?? '')}}">
      @if(count($divisis) > 1)
        <option value="">Pilih Unit Kerja</option>
      @endif
      @foreach($divisis as $divisi)
      @foreach($divisi->unit_kerjas as $unit_kerja)
        <option class="unit_kerja_option" 
                data-divisi_id="{{ $divisi->idDivisi }}" 
                value="{{ $unit_kerja->idUnitKerja }}" 
                {{ $unit_kerja->idUnitKerja == old('unit_kerja_id', $user->unit_kerja_id ?? '') ? 'selected' : '' }} 
                style="display: none;">
            {{ $unit_kerja->unitKerja }}
        </option>
      @endforeach
      @endforeach
    </select>
  </div>
</div>


<div class="form-group row">
  <label for="active" class="col-md-2 col-form-label text-md-right">Status</label>
  <div class="col-md-6">
    <select name="active" id="active" class="form-control">
        <option value="1" {{ old('active', $user->active ?? 1) == 1 ? 'selected' : '' }}>Aktif</option>
        <option value="0" {{ old('active', $user->active ?? 1) == 0 ? 'selected' : '' }}>Tidak Aktif</option>
    </select>
  </div>
</div>

<div class="form-group row">
  <label class="col-md-2"></label>
  <div class="col-md-6">
    <button type="submit" class="btn btn-primary">Submit</button>
    <button type="reset" class="btn btn-danger">Reset</button>
  </div>
</div>



@section('script')
@parent

<script type="text/javascript">
  $(document).ready(function(){
    $('#divisi_id').on('change', function(){
      var divisi_id = $(this).val();

      $('#unit_kerja_id').val("");
      $('.unit_kerja_option').each(function(){
        if ($(this).data('divisi_id') != divisi_id) {
          $(this).hide();
        } else {
          $(this).show();
        }
      });
    });


    setTimeout(function(){
      $('#divisi_id').trigger('change');
        var selected_unit_id = $('#unit_kerja_id').data('selected');
      $('#unit_kerja_id').val(selected_unit_id);
    }, 100);
  });
</script>

@endsection

resources/views/user/create.blade.php
@extends('layouts.main')

@section('title', 'Tambah user')

@section('content')
    <div class="row">
      <div class="col-lg-12">

        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Create User</h3>
            </div>
            <br>
                <form action="{{ route('users.store') }}" method="POST">
                    @include('user._form')
                </form>
            </div>
        </div>
          
      </div>
    <!-- /.row -->
@endsection

resources/views/user/edit.blade.php
@extends('layouts.main')

@section('title', 'Realisasi Kegiatan')

@section('content')
    <div class="row">
      <div class="col-lg-12">

        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Edit User</h3>
            </div>
            <br>
                <form action="{{ route('users.update', $user) }}" method="POST">
                    @method('PATCH')
                    @include('user._form')
                </form>
            </div>
        </div>
          
      </div>
    <!-- /.row -->
@endsection

resources/views/user/index.blade.php
@extends('layouts.main')

@section('title', 'Users')

@section('content')
<div class="row">
    <div class="col-lg-12">

        <div class="card card-success">
            <div class="card-header">
                <h3 class="card-title">List Users</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body p-0">
                <div class="p-2">
                    <div class="row">
                        <div class="col-md-4">
                            <form method="GET" id="search">
                                <div class="form-group">
                                    <input name="search" class="form-control" placeholder="Search" value="{{ old('search') }}">
                                </div>
                            </form>
                        </div>
                        <div class="col-md-2">
                            <a href="{{ route('users.create') }}" class="btn btn-primary">Create User</a>
                        </div>
                    </div>
                </div>
                <table class="table table-bordered table-hover table-responsive">
                    <thead>
                        <tr class="text-center">
                            <!-- <th class="align-middle">No</th> -->
                            <th class="align-middle">#ID</th>
                            <th class="align-middle">Nama</th>
                            <th class="align-middle">Nickname</th>
                            <th class="align-middle">Username</th>
                            <th class="align-middle">Email</th>
                            <th class="align-middle">Divisi</th>
                            <th class="align-middle">Unit Kerja</th>
                            <th class="align-middle">Role</th>
                            <th class="align-middle">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($users as $user)
                        <tr>
                            <!-- <td>{{ ($users->currentPage() - 1) * 10 + $loop->iteration }}</td> -->
                            <td>{{ $user->id }}</td>
                            <td>{{ $user->name }}</td>
                            <td>{{ $user->nickname }}</td>
                            <td>{{ $user->username }}</td>
                            <td>{{ $user->email }}</td>
                            <td>{{ $user->divisi->txtDivisi ?? '' }}</td>
                            <td>{{ $user->unitKerja->unitKerja ?? '' }}</td>
                            <td>{{ $user->roles->first()->name ?? '' }}</td>
                            <td>
                                <div class="d-flex">
                                <a class="btn btn-sm btn-primary" href="{{ route('users.edit', $user) }}"><i class="fas fa-edit"></i></a>
                                &nbsp;
                                <form id="delete-user-{{ $user->id }}" method="POST" action="{{ route('users.destroy', $user) }}" onsubmit="return confirm('Are You Sure to Delete : {{ $user->name }}')">
                                    @method('DELETE')
                                    @csrf
                                    <button type="submit" class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></button>
                                </form>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <div class="card-footer">
                {{ $users->appends(request()->input())->links() }}
            </div>
        </div>

    </div>
</div>
<!-- /.row -->
@endsection