routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();


Route::group(['middleware' => ['auth']], function () {
	
	Route::get('/', 'HomeController@index')->name('dashboard.index');
	Route::resource('/rencana-kegiatan', 'RencanaController');
	Route::get('/realisasi-kegiatan/{id_timesheet}/create', 'RealisasiController@create');
	Route::resource('/realisasi-kegiatan', 'RealisasiController')->except('create');
    Route::post('job-order/nilai', 'JobOrderController@addNilai')->name('job-order.add-nilai');
	Route::get('/job-order/{timesheet_id}/comment', 'JobOrderController@comment')->name('job-order.comment');
	Route::post('/job-order/{timesheet_id}/comment', 'JobOrderController@storeComment')->name('job-order.store-comment');
    Route::post('/job-order/{employee_id}', 'JobOrderController@store')->name('job-order.store');
	Route::resource('/job-order', 'JobOrderController')->except('store');
	Route::get('/report', 'ReportController@index')->name('report.index');
	Route::post('/report', 'ReportController@show')->name('report.show');
	Route::get('/chart', 'ChartController@index')->name('chart.index');
	Route::post('/chart', 'ChartController@show')->name('chart.show');

	Route::group(['middleware' => ['role:Admin']], function () {
        Route::resource('/users', 'UserController');
        Route::resource('/tanggal-libur', 'TanggalLiburController');

	});

});

Route::get('/asd', 'ChartController@asd');

Route::get('/home', function(){
    return redirect('/');
});

app/Models/TanggalLibur.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class TanggalLibur extends Model
{
    protected $table = 'tbl_libur';
    protected $primaryKey = 'idTgl_libur';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'idTgl_libur','tgl_libur', 'keterangan_libur'
    ];

}

app/Http/Controllers/TanggalLiburController.php
<?php

namespace App\Http\Controllers;

use App\Models\TanggalLibur;
use Illuminate\Http\Request;

class TanggalLiburController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tgl_libur = TanggalLibur:: all();
        //dd($tgl_libur);
        //URL /tanggal-libur
        // TAMPILKAN SEMUA TANGGAL LIBUR
        return view('tanggal-libur.index', ['TanggalLibur' => $tgl_libur]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // URL /tanggal-libur/create
        // TAMPILKAN FORM PEMBUATAN TANGGAL LIBUR
        // return view('file.edit.tanggal.libur');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //PROSES SIMPAN TANGGAL LIBUR BARU
        // return redirect(route('tanggal-libur.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\TanggalLibur  $tanggalLibur
     * @return \Illuminate\Http\Response
     */
    public function show(TanggalLibur $tanggalLibur)
    {
        // URL /tanggal-libur/123 {123 = Id Tanggal Libur}
        // BISA DI SKIP
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\TanggalLibur  $tanggalLibur
     * @return \Illuminate\Http\Response
     */
    public function edit(TanggalLibur $tanggalLibur)
    {
        // URL /tanggal-libur/123/edit {123 = Id Tanggal Libur}
        // TAMPILKAN FORM PEMBUATAN TANGGAL LIBUR
        // return view('file.edit.tanggal.linur', compact('tanggalLibur'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\TanggalLibur  $tanggalLibur
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, TanggalLibur $tanggalLibur)
    {
        //PROSES SIMPAN EDIT TANGGAL LIBUR
        // return redirect(route('tanggal-libur.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\TanggalLibur  $tanggalLibur
     * @return \Illuminate\Http\Response
     */
    public function destroy(TanggalLibur $tanggalLibur)
    {
        //PROSES HAPUS TANGGAL LIBUR
        // return redirect(route('tanggal-libur.index'));
    }
}

resources/views/tanggal-libur/_form.blade.php
<br>
@csrf

<div class="form-group row">
  <label for="Keterangan_libur" class="col-md-2 col-form-label text-md-right">Nama Hari Libur</label>
  <div class="col-md-6">
    
    <input type="text" class="form-control" rows="5" name="name" id="name" placeholder="Nama Lengkap" value="{{ old('name', $user->name ?? '') }}">
  
  </div>
</div>

<div class="form-group row">
  <label for="tgl_libur" class="col-md-2 col-form-label text-md-right">Nickname</label>
  <div class="col-md-6">
    
    <input type="text" class="form-control" rows="5" name="nickname" id="nickname" placeholder="XXX" value="{{ old('nickname', $user->nickname ?? '') }}">
  
  </div>
</div>

<!-- SELECT UNIT -->
<div class="form-group row">
  <label for="date" class="col-md-2 col-form-label text-md-right">Unit Kerja</label>
  <div class="col-md-6">
    <select name="unit_kerja_id" id="unit_kerja_id" class="form-control" data-selected="{{old('unit_kerja_id', $user->unit_kerja_id ?? '')}}">
      @if(count($divisis) > 1)
        <option value="">Pilih Unit Kerja</option>
      @endif
      @foreach($divisis as $divisi)
      @foreach($divisi->unit_kerjas as $unit_kerja)
        <option class="unit_kerja_option" 
                data-divisi_id="{{ $divisi->idDivisi }}" 
                value="{{ $unit_kerja->idUnitKerja }}" 
                {{ $unit_kerja->idUnitKerja == old('unit_kerja_id', $user->unit_kerja_id ?? '') ? 'selected' : '' }} 
                style="display: none;">
            {{ $unit_kerja->unitKerja }}
        </option>
      @endforeach
      @endforeach
    </select>
  </div>
</div>


<div class="form-group row">
  <label for="active" class="col-md-2 col-form-label text-md-right">Status</label>
  <div class="col-md-6">
    <select name="active" id="active" class="form-control">
        <option value="1" {{ old('active', $user->active ?? 1) == 1 ? 'selected' : '' }}>Aktif</option>
        <option value="0" {{ old('active', $user->active ?? 1) == 0 ? 'selected' : '' }}>Tidak Aktif</option>
    </select>
  </div>
</div>

<div class="form-group row">
  <label class="col-md-2"></label>
  <div class="col-md-6">
    <button type="submit" class="btn btn-primary">Submit</button>
    <button type="reset" class="btn btn-danger">Reset</button>
  </div>
</div>



@section('script')
@parent

<script type="text/javascript">
  $(document).ready(function(){
    $('#divisi_id').on('change', function(){
      var divisi_id = $(this).val();

      $('#unit_kerja_id').val("");
      $('.unit_kerja_option').each(function(){
        if ($(this).data('divisi_id') != divisi_id) {
          $(this).hide();
        } else {
          $(this).show();
        }
      });
    });


    setTimeout(function(){
      $('#divisi_id').trigger('change');
        var selected_unit_id = $('#unit_kerja_id').data('selected');
      $('#unit_kerja_id').val(selected_unit_id);
    }, 100);
  });
</script>

@endsection

resources/views/tanggal-libur/create.blade.php
@extends('layouts.main')

@section('title', 'Tanggal Libur')

@section('content')
    <div class="row">
      <div class="col-lg-12">

        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Tambah hari libur</h3>
            </div>
            <br>
                <form action="{{ route('tbl-libur.store') }}" method="POST">
                    @include('tanggal-libur._form')
                </form>
            </div>
        </div>
          
      </div>
    <!-- /.row -->
@endsection

resources/views/tanggal-libur/edit.blade.php
@extends('layouts.main')

@section('title', 'Tanggal Libur')

@section('content')
    <div class="row">
      <div class="col-lg-12">

        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Edit User</h3>
            </div>
            <br>
                <form action="{{ route('tbl_libur.update', $tanggal-libur) }}" method="POST">
                    @method('PATCH')
                    @include('tanggal-libur._form')
                </form>
            </div>
        </div>
          
      </div>
    <!-- /.row -->
@endsection

resources/views/tanggal-libur/index.blade.php
@extends('layouts.main')

@section('title', 'TanggalLibur')

@section('content')
<div class="row">
    <div class="col-lg-12">

        <div class="card card-success">
            <div class="card-header">
                <h3 class="card-title">List Tanngal Libur</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body p-0">
                <div class="p-2">
                    <div class="row">
                        <div class="col-md-4">
                            <form method="GET" id="search">
                                <div class="form-group">
                                    <input name="search" class="form-control" placeholder="Search" value="{{ old('search') }}">
                                </div>
                            </form>
                        </div>
                        <div class="col-md-2">
                            <a href="{{ route('tanggal-libur.create') }}" class="btn btn-primary">Tambah Hari Libur</a>
                        </div>
                    </div>
                </div>
                <table class="table table-bordered table-hover table-responsive">
                    <thead>
                        <tr class="text-center">
                            <!-- <th class="align-middle">No</th> -->
                            <th class="align-middle">#ID</th>
                            <th class="align-middle">Tanggal Libur</th>
                            <th class="align-middle">Keterangan Libur</th>
                            <th class="align-middle">Action</th>
                        </tr>
                    </thead>
                    
                    <tbody>
                        @foreach ($TanggalLibur as $tbl_libur)
                        <tr>
                            <td>{{ $tbl_libur->idTgl_libur }}</td>
                            <td>{{ $tbl_libur->tgl_libur }}</td>
                            <td>{{ $tbl_libur->keterangan_libur }}</td>
                            <td>
                               <div class="d-flex">
                                <a class="btn btn-sm btn-primary" href="{{ route('tanggal-libur.edit', $tbl_libur) }}"><i class="fas fa-edit"></i></a>
                                &nbsp;
                                <form id="delete-user-{{$tbl_libur->id }}" method="POST" action="{{ route('tanggal-libur.destroy', $tbl_libur) }}" onsubmit="return confirm('Are You Sure to Delete : {{ $tbl_libur->name }}')">
                                    @method('DELETE')
                                    @csrf
                                    <button type="submit" class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></button>
                                </form>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            
        </div>

    </div>
</div>
<!-- /.row -->
@endsection